spring.application.name=Asserts-SB

# Render provides the port dynamically
server.port=${PORT:4444}

# Railway MySQL Database Connection
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:39916/railway
spring.datasource.username=root
spring.datasource.password=SdIOiJikmmhnUtBegujEvDOfHaxptIry
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
